import type { EmployerPostedJob } from "@/types/employer-job";

export const employerPostedJobs: EmployerPostedJob[] = [
  {
    id: "job-senior-frontend-engineer",
    title: "Senior Frontend Engineer",
    slug: "senior-frontend-engineer",
    category: "Software Engineering",
    jobType: "Full-time",
    workMode: "Hybrid",
    location: "Austin, TX",
    salaryMin: 115000,
    salaryMax: 145000,
    currency: "USD",
    applicantsCount: 48,
    newApplicantsCount: 8,
    viewsCount: 1240,
    postedDate: "2026-06-12",
    expirationDate: "2026-07-31",
    status: "active",
    visibility: "public",
    employerId: "employer-ariana",
    companyId: "company-novatech",
  },
  {
    id: "job-product-designer",
    title: "Product Designer",
    slug: "product-designer",
    category: "Product & Design",
    jobType: "Full-time",
    workMode: "Remote",
    location: "United States",
    salaryMin: 98000,
    salaryMax: 128000,
    currency: "USD",
    applicantsCount: 31,
    newApplicantsCount: 5,
    viewsCount: 890,
    postedDate: "2026-06-04",
    expirationDate: "2026-07-18",
    status: "active",
    visibility: "public",
    employerId: "employer-ariana",
    companyId: "company-novatech",
  },
  {
    id: "job-customer-success-manager",
    title: "Customer Success Manager",
    slug: "customer-success-manager",
    category: "Customer Success",
    jobType: "Full-time",
    workMode: "On-site",
    location: "Denver, CO",
    salaryMin: 76000,
    salaryMax: 94000,
    currency: "USD",
    applicantsCount: 17,
    newApplicantsCount: 2,
    viewsCount: 532,
    postedDate: "2026-05-28",
    expirationDate: "2026-06-30",
    status: "inactive",
    visibility: "private",
    employerId: "employer-ariana",
    companyId: "company-novatech",
  },
  {
    id: "job-data-analyst-draft",
    title: "Data Analyst",
    slug: "data-analyst",
    category: "Data & Analytics",
    jobType: "Contract",
    workMode: "Hybrid",
    location: "Chicago, IL",
    salaryMin: 65000,
    salaryMax: 82000,
    currency: "USD",
    applicantsCount: 0,
    newApplicantsCount: 0,
    viewsCount: 0,
    postedDate: null,
    expirationDate: null,
    status: "draft",
    visibility: "private",
    employerId: "employer-ariana",
    companyId: "company-novatech",
  },
  {
    id: "job-growth-marketing-lead",
    title: "Growth Marketing Lead",
    slug: "growth-marketing-lead",
    category: "Marketing",
    jobType: "Full-time",
    workMode: "Remote",
    location: "North America",
    salaryMin: 104000,
    salaryMax: 132000,
    currency: "USD",
    applicantsCount: 24,
    newApplicantsCount: 0,
    viewsCount: 678,
    postedDate: "2026-05-10",
    expirationDate: "2026-06-20",
    status: "closed",
    visibility: "private",
    employerId: "employer-ariana",
    companyId: "company-novatech",
  },
  {
    id: "job-sales-development-representative",
    title: "Sales Development Representative",
    slug: "sales-development-representative",
    category: "Sales",
    jobType: "Full-time",
    workMode: "Hybrid",
    location: "Boston, MA",
    salaryMin: 56000,
    salaryMax: 72000,
    currency: "USD",
    applicantsCount: 39,
    newApplicantsCount: 4,
    viewsCount: 714,
    postedDate: "2026-06-01",
    expirationDate: "2026-07-15",
    status: "archived",
    visibility: "private",
    employerId: "employer-ariana",
    companyId: "company-novatech",
  },
];
